### ISSUE TITLE
Release of aarch64 wheels on pypi

### ISSUE THREAD

**Issue by odidev** [andrix/python-snappy#106]
@martindurant I can see all the wheels which are built using [ the PR #103](https://github.com/andrix/python-snappy/pull/103) are uploaded to pypi except for aarch64.
Are you facing any issues regarding aarch64 wheels upload?  Please let me know if I can help you with this.

**Comment by martindurant** [comment]
There were so many... Which are missing exactly?

**Comment by odidev** [comment]
Here is a list of missing aarch64 wheels on pypi (built via #103 )-

python_snappy-0.6.0-cp35-cp35m-manylinux2014_aarch64.whl
python_snappy-0.6.0-cp36-cp36m-manylinux2014_aarch64.whl
python_snappy-0.6.0-cp37-cp37m-manylinux2014_aarch64.whl
python_snappy-0.6.0-cp38-cp38-manylinux2014_aarch64.whl
python_snappy-0.6.0-cp39-cp39-manylinux2014_aarch64.whl

**Comment by martindurant** [comment]
Done! Sorry about that. Next time, all the wheels will be new, so there will be no filtering, all should go well.
