### ISSUE TITLE
bad argument to internal function error

### ISSUE THREAD

**Issue by facboy** [andrix/python-snappy#25]
I realise this is a somewhat nonsensical use-case, but if I do the following under Python 2.7.8 I get an error:

``` python
>>> import snappy
>>> snappy.decompress(snappy.compress(''))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: Objects/stringobject.c:3903: bad argument to internal function
```

Under Python 2.6.6 it seems to work (returns '').  If it helps, I noticed this trying to build avro (https://github.com/apache/avro/tree/trunk/lang/py) under Python 2.7.8.

**Comment by alexche8** [comment]
So, what the problem it was?

**Comment by dangra** [comment]
Unreproducible and line silence after 2 months I guess.

why asking? can you reproduce it?

**Comment by facboy** [comment]
very rude/lax of me to never reply.  must have been some junk on my local machine, just tried a pip install python-snappy and it was fine (CentOS 7.3, python 2.7.5).
