### ISSUE TITLE
Document framing format used

### ISSUE THREAD

**Issue by cowtowncoder** [andrix/python-snappy#27]
It sounds like a framing format is used over plain encrypted blocks (which is good). But it is not clear what format this would be, given that Snappy does not have standard one.
That is, there are multiple ones
- one used by https://github.com/dain/snappy (pure java snappy)
- one described in https://code.google.com/p/snappy/source/browse/trunk/framing_format.txt

I'd be guessing it might be second one, but would want to know, to make sure I am using compatible implementations.

**Comment by jtolds** [comment]
oh whoa, i had no idea it had gotten so complicated. good to know

**Comment by jtolds** [comment]
the bottom of https://code.google.com/p/snappy/issues/detail?id=34 in particular is why https://github.com/kubo/snzip surprised me. we really should standardize on the official one
