### ISSUE TITLE
another tip for the readme (osx and others)

### ISSUE THREAD

**Issue by jvanasco** [andrix/python-snappy#34]
This drove me crazy before my morning coffee sank in and I realized something was wrong when trying to install the dependency off the link.

Google moved the project to github and it splashes with an "organization" page.  The download touts for the snappy library on http://google.github.io/snappy default to the current MASTER git source - not an 'easily installable version'.  The active git version - which is linked to on the front page - needs to be installed via a package maintainer's workflow and requires a lot of environment setup (which is a complete f****** pain).  

If click into the project's full github page, and then the `releases` page (https://github.com/google/snappy/releases) to find an installable version (with configure and everything set up straight), the install process is a straightforward configure/make/install -- even on the core osx distribution.

**Comment by andrix** [comment]
I've checked and this is fixed now: http://google.github.io/snappy/. It redirect to a great page with details.
