### ISSUE TITLE
snappy.UncompressError: stream missing snappy identifier

### ISSUE THREAD

**Issue by ryanchou1991** [andrix/python-snappy#40]
When I used snappy module to decompress a file it occurs the issue

```
snappy.UncompressError: stream missing snappy identifier
```

**Comment by andrix** [comment]
The implementation for file compression/decompression using streaming was done by @jtolds. He may have a better idea of what's going on.

**Comment by jtolds** [comment]
There's two forms of Snappy compression, the basic form and the streaming form. The basic form has the limitation that it all must fit in memory, so the streaming form exists to be able to compress larger amounts of data. The streaming format has a header and then subranges that are compressed. If the header is missing, it sounds like maybe you compressed using the basic form and are trying to uncompress with the streaming form.

**Comment by ryanchou1991** [comment]
@jtolds so how to uncompressed with streaming form? any tutorial to help me figure it out?

**Comment by jtolds** [comment]
What did you do to uncompress the data? Can you paste the code you used? That way I can help with what needs to change.

**Comment by ryanchou1991** [comment]
@jtolds The following were the snappy cli I used.

```
python -m snappy -d ./02_1473019352277439472_14838198.snappy
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/snappy.py", line 305, in <module>
    cmdline_main()
  File "/usr/local/lib/python2.7/site-packages/snappy.py", line 301, in cmdline_main
    method(src, dst)
  File "/usr/local/lib/python2.7/site-packages/snappy.py", line 263, in stream_decompress
    buf = decompressor.decompress(buf)
  File "/usr/local/lib/python2.7/site-packages/snappy.py", line 192, in decompress
    raise UncompressError("stream missing snappy identifier")
snappy.UncompressError: stream missing snappy identifier
```

I dont know what's wrong with it. Please help me out with this issue.

**Comment by jtolds** [comment]
okay, the commandline tool only supports the streaming format. You will need to write a program that imports the snappy package and uses the plain uncompress method with the data from that file.

  import snappy, sys; sys.stdout.write(snappy.uncompress(file("./02_1473019352277439472_14838198.snappy").read()))

**Comment by ryanchou1991** [comment]
Oh. I got it. It works like a charm. Thanks a lot. It confused me so long, And why not provide an option to process the file?

**Comment by jtolds** [comment]
Because unframed snappy compression has a maximum size limit, so if you're dealing with files you almost certainly want the streaming format

**Comment by ryanchou1991** [comment]
OK. I got it.

**Comment by rajeevanair** [comment]
Hi,
I installed snappy package, but the module uncompress is not present. Kindly, help me with this.

Thanks,
Rajeev A. Nair

**Comment by martindurant** [comment]
@rajeevanair , can you please be more specific about your situation, how you installed, what versions you got and what you did to see the error.

**Comment by rajeevanair** [comment]
Hi Martin,
I installed python-snappy-0.5.1, using python setup.py install command.
Then I imported snappy using :
import snappy

However snappy library does not have an uncompress function.

**Comment by martindurant** [comment]
```
$ conda create -n test python cffi
$ source activate test
$ pip install git+https://github.com/andrix/python-snappy  # this is version 0.5.2
$ python
>>> import snappy
>>> snappyuncompress
<function uncompress at 0x108df7510>
```

**Comment by rajeevanair** [comment]
A thousand thanks, Martin! That worked.
