### ISSUE TITLE
Add wheels for linux and OSX?

### ISSUE THREAD

**Issue by Daenyth** [andrix/python-snappy#41]
It would simplify installation if we weren't required to compile locally but could instead get the wheel via pip

**Comment by andrix** [comment]
Can you send a PR?

**Comment by Daenyth** [comment]
I'm not sure how I can do that? It's something you need to do when uploading to pypi. You run `python setup.py bdist_wheel` to make the wheel files

**Comment by Daenyth** [comment]
https://packaging.python.org/distributing/#platform-wheels

**Comment by Daenyth** [comment]
This is a demo project of how to build manylinux wheels on travis https://github.com/pypa/manylinux

**Comment by jakirkham** [comment]
One thing we have been discussing and playing with at conda-forge recently is the option to build wheels as a second build product along with conda packages. This might be useful for projects like `python-snappy`. Discussion is happening in issue ( https://github.com/conda-forge/conda-smithy/issues/608 ). Some examples of how this might work are [outlined in this comment]( https://github.com/conda-forge/conda-smithy/issues/608#issuecomment-370359867 ).

**Comment by mbarkhau** [comment]
Just ran into this.

```
    snappy/snappymodule.cc:31:10: fatal error: snappy-c.h: No such file or directory
     #include <snappy-c.h>
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

Binary wheels on pypi would be a nice addition. @andrix I suppose by PR you might mean something for travis that builds wheels and uploads them to pypi?
