### ISSUE TITLE
Somebody Resurrect this Zombie Already

### ISSUE THREAD

**Issue by leycec** [andrix/python-snappy#42]
The ominous lack of commits and mounting number of outstanding issues and pull requests inescapably suggests this once-optimistic project to now be yet another a shambling GitHub zombie. <sup>_...and just in time for Halloween!_</sup>

**This saddens us all.** Would any intrepid unpaid volunteer with an open pull request mind producing an official, well-maintained fork of this project under a different name? I'm partial to [`mrsnips`](https://i.imgur.com/yov14NX.jpg) myself, but _anything_ will do. :scorpion: 

Let's just do _something_, people. It's time to fight commit inactivity with renewed vigour!

**Comment by jtolds** [comment]
I object to the suggestion that lack of recent commits means an uncared for or dead project. Sometimes software can be done! This library provides snappy compression and provides it well. Is it really the case that the only good software is software that is constantly changing? Please.

**Comment by jtolds** [comment]
Andrix has moved on from supporting pull request review and issue fixing, but the existence of pull requests and issues doesn't automatically mean Something Must Be Done.
