### ISSUE TITLE
Active Fork

### ISSUE THREAD

**Issue by mrocklin** [andrix/python-snappy#43]
This library appears to be both useful to the Python community and currently unmaintained.  This is normal, developers sometimes move on, but we should decide what to do.

@andrix would you be willing to transfer ownership of this library to someone else?  Also would you be willing to give someone else ownership rights over the package on PyPI?

**Comment by andrix** [comment]
@mrocklin Of course. The most important here is to keep python-snappy alive and up to date, and as a useful tool for everyone. Open and free. 
Unfortunately, I'm not having free time to spend on this at the moment as my family got bigger (2 kids) and too much work.

I think is a good idea to move the library to a separate repository github.com/python-snappy, and offer write permissions to others. Also, I'll share the ownership rights over PyPi.

**Comment by mrocklin** [comment]
Is there anyone you can think of who has worked on the project and might make a good maintainer in the future?  Looking at the currently open pull requests it appears that all of them were done by different individuals.

**Comment by andrix** [comment]
@mrocklin - I had the opportunity to chat with @jtolds and he is the other that has ownership on the repo. However, I believe he's busy as well. I don't have other candidates in mind.

**Comment by jtolds** [comment]
I'm totally swamped. I've certainly been trying to pitch in.

My personal opinion is that this library is pretty feature complete and stable though so I'm not sure much work is really needed? It's packaged and works great.

When you say it's unmaintained, what are you hoping to change about the code/project?

It's okay if a widely used package hasn't had new commits in a while, especially if it's feature complete.

**Comment by mrocklin** [comment]
There are several open PRs here: https://github.com/andrix/python-snappy/pulls

To be clear I'm not casting blame.  I've also left several projects over the years.

**Comment by aeroevan** [comment]
I took the opportunity to learn cython to add the hadoop framing format (one of the open PRs) to my pysnappy package.

**Comment by mrocklin** [comment]
@andrix would you feel comfortable granting me ownership writes to the PyPI account?  I'm willing to merge things and push updates (or find others who are able).  I probably won't contribute much to this repository personally, but am happy to administrate to a certain extent.

**Comment by andrix** [comment]
@mrocklin Sure, of course. I'm open to, as long as we can keep the development of the library active. You can drop me an email to andres (AT) andresmoreira.com, and we can disucss in private the rest.

**Comment by andrix** [comment]
@mrocklin and @martindurant both have become collaborators on the project, both belong to Continuum Analytics and I'm sure the project is in good hands. /cc @jtolds 

I hope the project can keep going.
