### ISSUE TITLE
Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2 on Windows 10

### ISSUE THREAD

**Issue by Khris777** [andrix/python-snappy#48]
I am trying to upgrade python-snappy and the install is failing:

```
C:\>pip install python-snappy --upgrade
Collecting python-snappy
  Using cached python-snappy-0.5.1.tar.gz
Building wheels for collected packages: python-snappy
  Running setup.py bdist_wheel for python-snappy ... error
  Complete output from command C:\Users\my.name\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\my.name\\appdata\\local\\temp\\pip-build-wukcy4\\python-snappy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\my.name\appdata\local\temp\tmprao6jypip-wheel- --python-tag cp27:
  WARNING: '.' not a valid package name; please use only .-separated package names in setup.py
  running bdist_wheel
  running build
  running build_py
  package init file '__init__.py' not found (or not a regular file)
  creating build
  creating build\lib.win-amd64-2.7
  copying setup.py -> build\lib.win-amd64-2.7
  copying snappy.py -> build\lib.win-amd64-2.7
  copying snappy_cffi.py -> build\lib.win-amd64-2.7
  copying test_snappy.py -> build\lib.win-amd64-2.7
  copying test_snappy_cffi.py -> build\lib.win-amd64-2.7
  running build_ext
  building '_snappy' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  C:\Users\my.name\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\my.name\AppData\Local\Continuum\Anaconda2\include -IC:\Users\my.name\AppData\Local\Continuum\Anaconda2\PC /Tpsnappymodule.cc /Fobuild\temp.win-amd64-2.7\Release\snappymodule.obj
  snappymodule.cc
  C:\Users\my.name\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\my.name\AppData\Local\Continuum\Anaconda2\include -IC:\Users\my.name\AppData\Local\Continuum\Anaconda2\PC /Tccrc32c.c /Fobuild\temp.win-amd64-2.7\Release\crc32c.obj
  crc32c.c
  c:\users\my.name\appdata\local\temp\pip-build-wukcy4\python-snappy\crc32c.h(56) : error C2054: expected '(' to follow 'inline'
  c:\users\my.name\appdata\local\temp\pip-build-wukcy4\python-snappy\crc32c.h(57) : error C2085: 'crc_init' : not in formal parameter list
  c:\users\my.name\appdata\local\temp\pip-build-wukcy4\python-snappy\crc32c.h(57) : error C2143: syntax error : missing ';' before '{'
  c:\users\my.name\appdata\local\temp\pip-build-wukcy4\python-snappy\crc32c.h(79) : error C2054: expected '(' to follow 'inline'
  c:\users\my.name\appdata\local\temp\pip-build-wukcy4\python-snappy\crc32c.h(80) : error C2085: 'crc_finalize' : not in formal parameter list
  c:\users\my.name\appdata\local\temp\pip-build-wukcy4\python-snappy\crc32c.h(80) : error C2143: syntax error : missing ';' before '{'
  error: command 'C:\\Users\\my.name\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```

I'm using Python 2.7.13 with Anaconda on Windows 10 and I have already succesfully installed python-snappy into my Anaconda environment in a previous version around the end of march.
Back then I went through several steps as detailed [here](https://stackoverflow.com/a/43135438/2756793) to get snappy working on Windows 10 and I succeeded, everything was working fine then.

Now the upgrade fails and I have no clue why that C error is appearing.

Could it be a problem with the `stdint.h`?

**Comment by Khris777** [comment]
I used a precompiled version from http://www.lfd.uci.edu/~gohlke/pythonlibs/ as a workaround and was able to install it without issues.

**Comment by martindurant** [comment]
I'm afraid I don't know much about compiling on cygwin. Hopefully someone else can chime in. Probably the build steps used by gohlke can be found somewhere and replicated, if that's a good solution.

**Comment by crossz** [comment]
Same error by using MSYS/MinGW. @martindurant is the crc32c.h compatiable with Microsoft Visual C++?

**Comment by martindurant** [comment]
So my guess is, no? I don't know.
We could really use some MS C++ help, if anyone on this thread can provide it. The fact that gohlke has a working version means it can be built!

**Comment by crossz** [comment]
Ok, Gohlke's team did a great job on Windows compiling. Most of us far from that. So, I guess, I should go back to Vagrant solution to stay with development on Linux, on which python-snappy is much easier.

**Comment by rakidedigama** [comment]
Python 2.7 is incompatible or does not support Visual C++ 14 that is required to compile C99 code. Link here : [https://wiki.python.org/moin/WindowsCompilers]
 This is the reason for the compilation errors. Installing a newer version of Python (3.6 recommended) and VS 2015 build tools is the way to go. 
![image](https://user-images.githubusercontent.com/26470435/42805566-cd0c4fa4-89b4-11e8-9658-3b12bba6f9ae.png)

**Comment by vaishnavi-amalladinne** [comment]
I had the same error and I understood the problem was with ujson version(some later versions)
for pip users  -> pip install ujson==1.35
for conda users -> conda install -c anaconda ujson==1.35
This worked for me on Windows10
