### ISSUE TITLE
Hadoop snappy format support

### ISSUE THREAD

**Issue by aleks-v-k** [andrix/python-snappy#61]
Hi.
Would you mind to include hadoop snappy compression format support? Here I've just implemented this (compression & decompression): https://github.com/aleks-v-k/python-snappy/tree/hadoop_snappy_format

I can make a PR if you will accept such changes.

**Comment by martindurant** [comment]
Yes, I think a PR is the best way to go.

**Comment by aleks-v-k** [comment]
Thanks, Iv'e jut created the PR.

**Comment by aleks-v-k** [comment]
Ok, the format is supported now (after PR #62 has been merged).
