### ISSUE TITLE
Is there anyway to merge two compressed streams into 1 snappy file

### ISSUE THREAD

**Issue by leilakarimi** [andrix/python-snappy#70]
I have a parallel function which is compressing large number of files using python-snappy. Is there a way to merge all the returned compressed streams into one snappy file?

Thanks in advance

**Comment by martindurant** [comment]
I don't believe there is a thing as a "snappy file" in the sense that you mean, as used in zip. If you simply want to include a stream of compressed chunks, StreamCompressor is the place to look.

**Comment by Leila-karimi** [comment]
Thanks @martindurant for your reply! I guess my question is whether the snappy streams are combinable? What I want to do is to combine compressed streams into one. I can do this in gzip and combine all the gz streams into 1 gz file/stream. But, with snappy it's like there is a header making each compressed stream unique and not combinable, am I right? 

   ```
            buffer =io.BytesIO()
            with gzip.GzipFile(fileobj=buffer, mode='wb', compresslevel=6) as gzip_file:
                gzip_file.write(single_stream_to_be_zipped)
-------------------------------------------------------------------------
            with io.BytesIO() as out_gzip_file:
                for in_buffer in multiple_gz_file_streams:
                    out_gzip_file.write(in_buffer.getvalue())

```

**Comment by leilakarimi** [comment]
Thanks @martindurant for your reply! I guess my question is whether the snappy streams are combinable? What I want to do is to combine compressed streams into one. I can do this in gzip and combine all the gz streams into 1 gz file/stream. But, with snappy it's like there is a header making each compressed stream unique and not combinable, am I right?
```

         buffer =io.BytesIO()
         with gzip.GzipFile(fileobj=buffer, mode='wb', compresslevel=6) as gzip_file:
             gzip_file.write(single_stream_to_be_zipped)
-------------------------------------------------------------------------
         with io.BytesIO() as out_gzip_file:
             for in_buffer in multiple_gz_file_streams:
                 out_gzip_file.write(in_buffer.getvalue())

```

**Comment by leilakarimi** [comment]
When I try to combine the snappy streams into 1 stream this is what I get:

>  "stream received unskippable but unknown chunk")
> UncompressError: stream received unskippable but unknown chunk

**Comment by leilakarimi** [comment]
So, I've got
