### ISSUE TITLE
How to install snappy on Mac OS

### ISSUE THREAD

**Issue by Khan745** [andrix/python-snappy#87]
I'm having trouble install snappy into virtual environment. I'm using python3.6.6.

I try install snappy with commands:
$ sudo port install snappy
and:
(venv) xxx$ CPPFLAGS="-I/usr/local/include -L/usr/local/lib" pip install python-snappy

But after import I get error message:
ModuleNotFoundError: No module named 'snappy._snappy_cffi'

**Comment by Khan745** [comment]
mac port is not working. I use` brew install snappy` instead of `sudo port install snappy` and now it works

**Comment by anwer315** [comment]
1. Open Terminal by pressing command+space then type terminal and hit Enter key.
2. Install homebrew first.
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
3. Install snappy.
brew install snappy
Now, use snappy!
