### ISSUE TITLE
decompress returns empty result

### ISSUE THREAD

**Issue by Khris777** [andrix/python-snappy#89]
I have a snappy-compressed parquet file created in and downloaded from an older Hadoop/HDFS system which I'm trying to uncompress like this:

```
with open(snappy_file, "rb") as input_file:
    data = input_file.read()
    decompressor = snappy.hadoop_snappy.StreamDecompressor()
    check = decompressor.check_format(data)
    uncompressed = decompressor.decompress(data)
```

The value of `len(data)` is 29395108, but the result `uncompressed` is an empty byte. The value of `check` is `None` as it's supposed to be according to the docstring.

There is no error, no warning, nothing, just an empty output.

The docstring of `decompress` reads
`Decompress 'data', returning a string containing the uncompressed
        data corresponding to at least part of the data in string. This data
        should be concatenated to the output produced by any preceding calls to
        the decompress() method. Some of the input data may be preserved in
        internal buffers for later processing.`

This sounds rather fuzzy and I don't understand it fully, I tried to do multiple calls to the method, but still only empty output.

Any help is greatly appreciated.

OS: Windows 10
Python: 3.7.6
Snappy: 1.1.8
Python-Snappy 0.5.4

**Comment by martindurant** [comment]
Caveat: in general, parquet files are *not* snappy-compressed, but have internal compression of the binary chunks, so you normally do not need to decompress the whole file as you are doing.

However...

You should not need to do more than
```
with open(snappy_file, "rb") as input_file:
    data = input_file.read()

uncompressed = snappy.decompress(data)
```
With the "stream" decompressor you are invoking, there are extra considerations, I believe.

You might also try in-built compression of `fsspec`, which does something similar, like
```
import fsspec
with fsspec.open('snappy_file', 'rb', compression='snappy') as f:
    uncompressed_data = f.read()
```

**Comment by Khris777** [comment]
Thank you for your comments., it looks like that file is indeed not snappy compressed, so my issue seems to be rooted somewhere else.

It would be helpful for snappy decompression to throw a warning or an error when getting a file that isn't snappy compressed.

**Comment by martindurant** [comment]
Happy to accept PRs :)
