### ISSUE TITLE
Could you upload python3.7 python3.8 wheel to pypi.org?

### ISSUE THREAD

**Issue by hungrybirder** [andrix/python-snappy#93]
RT

Thank you.

**Comment by hungrybirder** [comment]
Hi, 
Any progress on this issue?

**Comment by martindurant** [comment]
This being a partially binary package, we would need wheels for each OS (linux, osx, win) and python version (36, 37, 38?). 
Fortunately, conda-forge does all this automatically, so I personally always recommend using conda for installing binary dependencies, which also includes the c-lib (i.e., you wouldn't need to get/compile snappy itself).

**Comment by ynouri** [comment]
I agree Conda might be the right solution 80% of the time, but for the remaining 20% I think the community would benefit from wheels for at least Linux / recent Python versions.

One example (I think among many): SageMaker enables you to install Python dependencies on-the-fly, but only through requirements.txt. Their base Docker images don't provide `libsnappy-dev` or `python-snappy`. Hence it's not possible to install `python-snappy` on-the-fly, and a fix in SageMaker base images is necessary: see https://github.com/aws/deep-learning-containers/issues/760. If Linux wheels were available this fix wouldn't be needed downstream.

I'm not familiar with the internals of Snappy - would it be challenging to build [manylinux wheels](https://github.com/pypa/manylinux) in the CI?

PS: for other OSes, I see that [MacOS and Windows containers are available in Github Actions](https://github.com/features/actions), not sure how difficult it is to build in those non Linux containers.

**Comment by martindurant** [comment]
> would it be challenging to build manylinux wheels in the CI

I invite anyone interested to try with https://github.com/marketplace/actions/python-wheels-manylinux-build . CI should move from travisCI to GH-actions anyway.

**Comment by ynouri** [comment]
I have something that seems to be working for Linux x86-64 / CPython 3.5 to 3.9:

![image](https://user-images.githubusercontent.com/1789921/101235272-34df2b80-3695-11eb-92b7-180c0d8210ad.png)

**Comment by ynouri** [comment]
PR re-opened under #101

**Comment by Czaki** [comment]
I may help with implement cibuildwheel usage which will allow simple build wheels for Linux, maxos and windows for both CPython and PyPi.
https://github.com/joerick/cibuildwheel/

**Comment by martindurant** [comment]
@Czaki , certainly sounds like a decent framework, and has lots of established users. What would need to happen at this end, are you wanting to implement this in a PR?

**Comment by Czaki** [comment]
@martindurant I created PR #103. It works for Linux and macOS. I have a problem with Windows. Maybe someone with windows experience could help.

**Comment by Czaki** [comment]
It works now for windows (except for CPython and pypy 2.7)
