### ISSUE TITLE
build fails with snappy-c.h: No such file or directory

### ISSUE THREAD

**Issue by vaibhav-rbs** [andrix/python-snappy#95]
OS:
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.2 (Ootpa)

python:
python -V
Python 3.6.8

(venv) [root@sl2rhel8snappy01 python-snappy]# python setup.py build
/usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'cffi_modules'
  warnings.warn(msg)
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/snappy
copying snappy/snappy.py -> build/lib.linux-x86_64-3.6/snappy
copying snappy/snappy_cffi.py -> build/lib.linux-x86_64-3.6/snappy
copying snappy/__init__.py -> build/lib.linux-x86_64-3.6/snappy
copying snappy/hadoop_snappy.py -> build/lib.linux-x86_64-3.6/snappy
copying snappy/snappy_formats.py -> build/lib.linux-x86_64-3.6/snappy
copying snappy/__main__.py -> build/lib.linux-x86_64-3.6/snappy
copying snappy/snappy_cffi_builder.py -> build/lib.linux-x86_64-3.6/snappy
running build_ext
building 'snappy._snappy' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/snappy
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/vchauhan/venv/include -I/usr/include/python3.6m -c snappy/snappymodule.cc -o build/temp.linux-x86_64-3.6/snappy/snappymodule.o
snappy/snappymodule.cc:31:10: fatal error: snappy-c.h: No such file or directory
 #include <snappy-c.h>
          ^~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by sjschubert** [comment]
You need to install the native snappy lib. Depending on your OS, the docs say:

> You can install Snappy C library with following commands:
> 
>     APT: sudo apt-get install libsnappy-dev
>     RPM: sudo yum install libsnappy-devel
>     Brew: brew install snappy
>

**Comment by vaibhav-rbs** [comment]
@sjschubert so we were able to figure out this problem at work, please note for that this problem Red Hat Enterprise Linux release 8.2 can be resolved if you take following steps. I think it would make lot more sense if this section was included in README

```
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.2 (Ootpa)

dnf install snappy-devel

```
